name: I_BEG_YOU_PLEASE_NO_RACE_NO_BUG

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: warchant/setup-mold@v1
      with:
        version: 1.2.1
        make_default: true
    - uses: icepuma/rust-action@master
    - name: Build
      run: cargo build --verbose
    - name: Rudra
      uses: sslab-gatech/Rudra@master
    - name: Run tests
      run: cargo test --verbose
